### ISSUE TITLE
BUG: Apollo Block II CM RCS effects on constant

### ISSUE THREAD

**Issue by icedown** [CobaltWolf/Bluedog-Design-Bureau#366] opened 2018-01-10 23:14 UTC
After undocking the LEM and going to the surface, when I returned, all of the RCS jet effects on the CM were active.  I had left RCS enabled when I undocked.  Use or toggling of the RCS did not make any change.  The effect is just present, the RCS is not active.
![screenshot5](https://user-images.githubusercontent.com/9828412/34800492-fbb6c972-f631-11e7-83cd-a59fa46d4ced.png)

**Comment by CobaltWolf** [comment] 2018-01-11 14:26
Ice, can you verify that it continues to happen? iirc effects bugs like
that sometimes are just the game glitching and will go away with a restart.
If its still happening I can try and see what's up.

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017

**Comment by icedown** [comment] 2018-01-12 01:25
It does require a restart, but all three times I have been to the Mun with the full Saturn V configuration it has happened.  I'll do some more testing with it later today to see if I can pin down some more concrete conditions.

**Comment by CobaltWolf** [comment] 2018-01-15 16:18
Let me know, but as far as I know this is just stock weirdness.

**Comment by CobaltWolf** [comment] 2018-01-24 17:58
@icedown anything to report? I'd like to close this if its outside out hands.

**Comment by icedown** [comment] 2018-01-25 13:18
I have been able to reproduce it every time I leave the CM in another ship and come back to it without leaving the flight scene.  If I do leave the flight scene, it does not occur.

**Comment by jsolson** [comment] 2018-01-25 19:45
Can not duplicate. That said, I've seen this before so I do believe you. Could you attempt:

a. Try to reproduce it with a stock only parts vessel.
b. Try to reproduce it in an install with only BDB and it's depencencies.

We do nothing fancy with RCS. I suspect this is a stock bug or a mod conflict. You might try asking in the Support-Modded Installs forum to see if this is a known issue.

**Comment by jsolson** [comment] 2018-03-06 22:12
>I was able to reproduce the RCS bug by cheating to orbit with a CSM+LEM. Undocking the LEM and leaving physics range, then returning. On return the CM thruster effects are firing. A scene change clears the issue.

>It does not happen when I change the root part from the CM to the service module. This looks like yet another stock root part related bug.

Switching to ModuleRCS seems to fix it. I'm going to do that with the CM and LEM since the LEM could conceivably be a root part.

**Closed** 2018-10-02 20:31 UTC
Labels: Needs testing, bug, confirmed
