### ISSUE TITLE
Tech tree placement issues

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#189] opened 2016-10-01 21:13 UTC
The Prometheus I parts are all in General Rocketry, except for the 1.5m Decoupler, which is in General construction. Is this intentional? It seems like all the essential parts for a particular rocket should be in the same node, though not necessarily the upgrades.

**Comment by CobaltWolf** [comment] 2016-10-01 22:46
I believe the intent was to try and match stock, where the structural parts are separate in the construction line.

**Comment by IronCretin** [comment] 2016-10-01 23:03
But none of the other early rockets do that, and it makes no sense.

**Comment by jsolson** [comment] 2016-10-02 00:25
Sorry, I didn't catch this discussion before merging it. Do we want the change or not?

**Comment by CobaltWolf** [comment] 2016-10-02 02:56
are the other stack decouplers like that?

**Comment by IronCretin** [comment] 2016-10-02 23:38
- The 625m decoupler is in the Start node
- The Vanguard parts in the Start node
- The Thor 9375 and 125m decouplers are in Engineering 101
- The Redstone and Diamant parts are in Basic Rocketry
- General Rocketry has Titan I, Juno, Thor, and Atlas
- Adv. Rocketry has Jupiter Engines, Agena D, and Titan I solids

I'll see if I can make a picture

Now that you've explained it, I think it's okay if the decouplers are separate (maybe move the adapters to join them though), though if it was up to me, you'd unlock things by stage.

**Comment by IronCretin** [comment] 2016-10-02 23:49
Related, the S-IV Instrument Unit is in Large Probes, at Tier 9, while the rest of the S-IV parts are in Adv. Fuel Systems, at Tier 6. I think it should be moved down to Unmanned Tech, where the S-IVB IU is (Tier 7) or Specialized Control (Tier 6)

**Comment by CobaltWolf** [comment] 2016-10-03 00:23
I think we should better define how launchers should be split up, and arranged, moving forward. Some things that I have tried to keep in mind so far:
>Launchers generally have followed something similar to stock, where they are arranged in order of size, rather than very strictly historical progression. Whereas other stuff is meant to be historical. 
>However, more advanced things in a certain size class are placed later. See, Titan variants, Delta 2, etc.
>Atlas has to come early enough to be useful for Mercury. There will be too many complaints otherwise.
>generalRocketry is overpopulated. I thought we had moved Titan 1 to advRocketry, but I also see it as comparable (and in some ways inferior) to Atlas.
>The 'Thor' decouplers were more meant to be generic parts for those size classes. Same for the fairing bases. The adapters don't visually fit in with other launchers and I need to look into that. 

I like the idea of unlocking things by stage, though I think splitting the parts along the stock branches works as well.

The Saturn IU is an oversight. I think we need to have a talk about Saturn. What should we do with it? IMO, Saturn 1, 1B, and V are the same tech level. However, I think letting the players make the crazier early Saturn variants first would be cool. Think A2, B1, where the upper stages were clusters like the first stage. I'd like to distinguish between the canon Saturn models, and the later proposals for expansion. I don't think I want Saturn V to be the end of the tech tree, especially if we have bigger stuff coming.

**Comment by jsolson** [comment] 2016-10-03 01:12
We want to stay as stockalike as possible here rather than try to improve on the stock tech tree. There are other tech trees we can use.

The F1s need to be in Very Heavy Rocketry at the end of the line. They outclass the Squad engine in there.
J2 and H1s 1 level below. Work backwards from there.
I do not think it should be necessary to research all the way down the Unmanned Tech line just to get the instrument units. They are glorified SAS units, not advanced probe cores, so consider Advanced Flight Control.
The engine mounts could be relocated to the same node as the engines, since if these were Squad parts they would be one big part. Interstage adapters as well would be just moduleJettison stuff so don't make them too hard to reach.

Everything we have is low tech, just big, so it shouldn't be needed to research through the whole bottom half of the tech tree to build an LV.

**Comment by IronCretin** [comment] 2016-10-03 02:15
Tech tree up to tier 4: ( think I got everything)
![techtree](https://cloud.githubusercontent.com/assets/708770/19025946/b8c518c4-88ed-11e6-873b-19d1642c09b5.png)

**Comment by jsolson** [comment] 2016-10-03 03:57
This is great. I wonder if the SM's shouldn't unlock in the same node as the associated CM.

**Comment by CobaltWolf** [comment] 2016-10-03 04:40
You mean move them to a propulsion node of the same tier? I actually think they're fine unlocking with the CM. The propulsion line seems more fitting for LVs. Maybe later on, when they split more, it makes sense to split them. O think various Apollo project stuff should be sprinkled thru out the later tech tree, think CSM variants, AAP stations and stuff... The problem is, since the tech tree is based on gameplay, and ends around Apollo level stuff, there isn't that much farther we can go. Anything we put there will be on the same level as high end colonization and interplanetary propulsion from other mods. Off the top of my head. 

Its worth noting that we can add tech nodes without a plugin ever since 1.0. Don't forget that as an option.

**Comment by jsolson** [comment] 2016-10-03 05:43
I mean the exact same node as the CM, since it part of the spacecraft. I'm the wrong person to ask, I can't stand the stock tech tree.

Wouldn't adding nodes be a recipe for conflict with another mod?

**Comment by IronCretin** [comment] 2016-10-03 15:13
![techtree](https://cloud.githubusercontent.com/assets/708770/19042544/6ddc8ea6-895a-11e6-9746-4b35d63812ca.png)

**Comment by IronCretin** [comment] 2016-10-03 15:19
This should be the whole thing, barring a few minor bits like antennas & experiments.
![techtree](https://cloud.githubusercontent.com/assets/708770/19042740/2d0d34d8-895b-11e6-9727-b1a1fbb17a39.png)

**Comment by CobaltWolf** [comment] 2016-10-03 15:22
Shit. We're all over the place...

Also, id recommend you close/delete your branch and start a fresh one after each pull request. I gather Jso and Komodo had a bit of a hectic night trying to sort out conflicts. 

-----Original Message-----

**Comment by IronCretin** [comment] 2016-10-03 15:23
I did delete mine, I'm sorry for any trouble I caused

**Comment by IronCretin** [comment] 2016-10-03 17:30
Here's a rough Idea of what I'd do with the saturn parts if it was up to me:
![techtree](https://cloud.githubusercontent.com/assets/708770/19046906/8b416670-896d-11e6-96a2-0aad900d7234.png)

**Comment by IronCretin** [comment] 2016-10-03 18:49
Dependencies: (maybe I'll jus make my own tech tree)
![chart](https://cloud.githubusercontent.com/assets/708770/19049439/736f0e48-8978-11e6-8b7d-f9297be40c67.png)

**Comment by IronCretin** [comment] 2016-10-03 19:16
Here's the mod I'm looking for: http://forum.kerbalspaceprogram.com/index.php?/topic/131112-wip-historical-progression-tree-jan-31-2016/

**Comment by jsolson** [comment] 2016-10-03 20:33
The Scimitar could probably go with the Apollo stuff, or at the very least much much closer to Start. And the S-IVB IU is annoying deep in the Tech/Science branch. The LO Engine is annoying deep too in miniaturization, but I can see the logic (although following that logic Explorer should be there as well).
FYI, there are two upgrades for the Atlas booster engines giving you early mid and late (Atlas II) versions, and 1 for the RL-10 making it the modern A4. Look in the engine configs for details.

I like your tree. In my tree that's what the engines branch would look like. Most of the tanks/structural stuff would be unlocked pretty early.

Don't forget about Community Tech Tree. That one may have more space for all our stuff. I've never used it but will be giving it a look on my next go around.

**Comment by CobaltWolf** [comment] 2016-10-04 13:24
LO engine was there because it's a later probe in the Apollo program. Scimatar should go with Apollo now that the craft it belongs with is in game.

I think we should just take a quick pass on the Saturn / Apollo stuff to make sure it generally unlocks in the same tier, then worry about a bigger look at the tech tree in the next dev cycle.

**Comment by CobaltWolf** [comment] 2016-10-18 20:27
There's a lot of strangeness that I'm noticing as I'm noodling around a basically stock+BDB career today at the lab:
- [ ] the 0.9375m decoupler should go in Engineering 101. Maybe move the other one (with the adapter) back to the starting node?
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by CobaltWolf** [comment] 2016-11-03 16:04
> With the addition of new parts, many with temporary tech tree placements, the mod needs a rebalance. Current issue is - should the tree be condensed, or should Sat-V be endgame?

> Leaning to condensed, to give space for ETS, Comet, ect. without needing CTT.

**Comment by SixDasher** [comment] 2016-11-03 16:50
Techtrees... can't live with them, can't delete them. The idea is good, but it's hard to implement correctly. The Saturn V being unlocked in too many nodes at the end of the techtree means it is not suited for career games, where you will be going to the outer planets where the Saturn will no longer be suited. I would not put it in too far up the techtree, and in 2-3 nodes total so you can actually use it for career play in the brief moment you actually want to go to the moon still (first 10 launches, after that you are headed to Duna or the outer planets.

The entire science system is unbalanced (I get 8K science from a single biome-hopping mission to minmus), making the techtree even harder to balance out.

**Comment by CobaltWolf** [comment] 2016-11-03 16:52
I still want to include a BDB-Extras folder. One of the things would be something that multiplies all the science experiment base values (including for other mods - remember it would be an informed decision by the player to install it) by some amount, and then another one that maybe would multiply the science needed for node unlocks... the game is just too fast!

**Comment by SixDasher** [comment] 2016-11-03 17:33
I've already pacthed labs to only do 1x instead of 5x, which still means you get double the science (once for the lab, second time to actually collect it). The CTT is sort of an improvement as you have more nodes and ones that go up to 10K science to unlock. I'm playing that in my new 1.2 career to see if that is more balanced in combination with 1x science lab returns.

**Comment by CobaltWolf** [comment] 2016-11-03 21:33
Yeah. Cus ideally you'd have time to sort of design, iterate launchers and crew vehicles in each tech level, for the MOS stuff have time to actually put up a station and get some operations out of it...

**Comment by CobaltWolf** [comment] 2016-11-05 19:40
Any feelings on this that @minepagan made? 
https://lh6.googleusercontent.com/hjEb1S0VDjgVfB6NqzyCOs69SEmRxJzfNRmGm7lBIEM5x7zo0UXX8A=w1200-h630-p

**Comment by jsolson** [comment] 2016-11-05 22:13
I like that. I would consider putting Atlas V post Saturn V somewhere. Even in KSP terms the RD-180 is more advanced than the F1. Same with the USRM boosters for the Titan IVB.

Not sure if stretching the Thor->Delta evolution all the way to the Heavier Rocketry level (tier 5) is possible with the part selection but that would seem to make sense.

Agena D and Centaur D and Vega and maybe Transtage should probably be parallel, with Centaur D leading to the S-IVB, but I'm not sure there's room for that.

I'm not really considering ETS stuff which will end up crammed. Perhaps Atlas V/USRM and the S-1E can go together.

**Comment by CobaltWolf** [comment] 2016-11-06 18:57
also remember that there's going to be advanced Saturn MLV stuff coming down the line too... honestly if you run out of room, just shoving it all into the last node is probably fine. Leave an IOU note.

OR, perhaps a MM config that activates if no tech tree is installed, that adds another node or two...

**Comment by SixDasher** [comment] 2016-11-06 20:25
SSTU does that with some of it's engines; just adds a node and redirects the previous one if people are using stock trees. CTT is an option, it is the stock tree with some extra lines splitting around the start and having 3 node layers added to the back of the tree for future tech stuff. It allows you to put stuff in seperate branches but at the same tech levels, or put stuff further down the line. I think it's the more popular option. ETT tries to rearrange the whole techtree and does not go well with mods that do not have their own ETT patch.

**Comment by jsolson** [comment] 2016-11-21 10:32
Could we move the Atlas launch clamps down to General Rocketry with the rest of Atlas? It looks silly sitting on a redstone launch clamp.

**Comment by minepagan** [comment] 2016-11-21 13:43
I thought I had moved it to the same tier? If not it needs to be. Also, there needs to be some sort of way to go from 3.75m-1.875m when you unlock the S-Ia stage (for Juno-V)

**Comment by jsolson** [comment] 2016-11-22 11:15
Moved it. None of them were working, I guess we renamed them on you. https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/07afa881c74a54d88fd4a56bdbc355b8bf565811

**Comment by minepagan** [comment] 2016-11-22 13:58
Oh I uploaded a fixed one a week or 2 ago, but it hasn't been integrated...

**Comment by minepagan** [comment] 2016-11-22 14:05
Nvm, I see what you mean with the name changes. I should be able to look at the rest in class today.

**Comment by jsolson** [comment] 2016-11-22 21:50
Are you working on these? I don't want to create more edit conflicts if you are. In the Gemini file, the docking port is listed twice. The last two parts have camel case typos, should be "generalConstruction". I'm suspicious that case errors like that only cause the part to be hidden in career games, because I never noticed the missing docking port in sandbox.

**Comment by minepagan** [comment] 2016-11-22 21:56
Yeah I was working on this, but I'm always happy for people to point out things I missed. I think I fixed that in the latest version, but I'll check in a bit? I might jahe missed them 

On a other note, does anyone know how to deal with the upgrades for engines? Or even add more?

**Comment by jsolson** [comment] 2016-11-22 22:11
>On a other note, does anyone know how to deal with the upgrades for engines?

`@PARTUPGRADE[bluedog_Atlas1]
{
@techRequired = advRocketry
}`

>Or even add more?

Look around in the atlas booster and centaur rl-10 configs. ModuleEngines has UPGRADES, there's a PartStatsUpgradeModule, and PARTUPGRADE at the bottom (same file but separate from the part).

Do _**not**_ add more.

**Comment by minepagan** [comment] 2016-11-23 01:27
I wasn't going to add more, just curious for future reference.
I'll try and crank out an updated techtree file with all these fixes, and the part upgrades moved, soon! (tm)

**Comment by minepagan** [comment] 2016-11-24 02:13
[Centaur.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/610349/Centaur.txt)
So, I seem to be encountering a problem with the interstage adapters, fairing base, and the engine upgrade. Are you sure that is the right syntax for the upgrade?
Also, am I just stupid and missing something?

**Comment by jsolson** [comment] 2016-11-24 12:31
~~~
//not working, need to fix -- syntax error below...
@PART[bluedog_centaur1875mAdapterFairing]
} <----- This is backwards. MM silently stops reading the file on syntax errors like this. Very hard to find.
	@TechRequired = generalRocketry
}
//not working, need to fix -- ok when above is fixed
@PART[bluedog_Centaur_FairingBase]
{
	@TechRequired = generalConstruction
}
//not working, need to learn/find proper code. Not really sure if it should be changed though....
@PARTUPGRADE[bluedog_RL101]
{
	@TechRequired = precisionPropulsion // It's lower case "t" techRequired in PARTUPGRADE. Going crazy yet?
}
~~~

It appears patching PARTUPGRADE like this doesn't work. With the errors fixed I can see in the ModuleManager.ConfigCache the changes are there, but it's not updated in the tech tree. I even tried changing the title, didn't show up.

**Comment by minepagan** [comment] 2016-11-24 15:50
Ahhhhhh! Now I feel really stupid, especially considering I stared at it for a few hours and still missed it. I should be able to put out the rest of the files once I get back to my computer, as they were all working right.

**Comment by FoxxoniusAugustus** [comment] 2016-11-26 15:31
Not sure if it should go here or should be a separate issue. In the currant dev build the Gemini docking port doesn't show up anywhere in the tech tree. To be clear I am talking about the _Gemini_Port_A or the Leo-M-C32 Nose Docking Mechanism in game.

**Comment by minepagan** [comment] 2016-11-26 15:56
Last time I checked it showed up with the Gemini SM parts, but I'll take a look before I push out the tree rebalance update later tonight.

**Comment by minepagan** [comment] 2016-11-27 00:59
Alright guys, @jsolson just merged the pull request, tree pass 3 is live! Thank you @FoxxoniusAugustus for pointing out the gemini bug, I've fixed that in the latest version! Tell me what you guys think, and how it works in game!

**Comment by jsolson** [comment] 2016-11-28 23:35
In my playthough Agena D comes up very fast. That probably should go to General Construction. I'm wondering if we introduce the Centaur in General Construction as well, we could do the cryo progression - Centaur, S-IV, S-IVB, S-II, J-2 and advanced J-2s in the General Construction, Advanced Construction, Specialized Construction, Composites path.

Delta K shows up before Delta II.

**Comment by minepagan** [comment] 2016-11-29 04:10
My bad on the delta stuff, I really need to do some research/testing for that....
About Atlas.....are you playing with reduced science gains? Its supposed to come on rather quickly, because otherwise we'd have to move everything back -  and that would leave no room for future Saturn-V derived MLVs.
In fact, the first 3 teirs are quite compressed, but there really is no other way to do it, without modding the tech tree itself - which would cause so many compatibility issues I don't even want to think about it.

**Comment by jsolson** [comment] 2016-11-29 04:43
Agena D, not Atlas. Yes it's compressed. I'm suggesting we go a little sideways.

**Comment by CobaltWolf** [comment] 2016-11-29 05:32
Yeah, that was my thought. Try and make sure things like structural parts go in construction nodes rather than the associated rocketry nodes for their launchers, etc. The placement of Agena control block and antenna, the RCS booms etc in the Stability node was something I was fond of. I don't know about avionics - they're not valuable enough to make people try and go for them IMO. 

-----Original Message-----

**Comment by jsolson** [comment] 2016-11-29 17:53
This is what I mean by "sideways". Not sure how non-cryo upper stage development fits into that though.

![](http://i.imgur.com/I3bi6gV.png)

**Comment by CobaltWolf** [comment] 2016-11-29 18:46
They can go in that line, between the pink and the highlighter color - the one that terminates and is replaced by the nuclear stuff. There isn't that much non-cryo upper stage stuff for us to do; most US upper stage development has focused on cryogenics. The only important one to consider would be the Delta K...

Some random thoughts - Vega, Agena D, and the Juno IV stuff should come around the same time as each other. Possibly along with Ablestar (which is basically the Delta upper stage until you get to the Delta P), though you could justify that unlocking with Agena A as well. The big difference between Agena B and D is the engine - the Agena B basically was a D length fuel tank with the A engine, though there were a lot of other changes as Agena D was the 'standardized' version meant for serial production. 

@minepagan I can't start up the game right now, but how are the early launchers distributed through the first few tiers? I know you moved some up into Basic Rocketry, etc. Are Redstone and Vanguard in the starting node? There's a case to be made for Diamant being there too (similar technology levels, first French launcher, etc) but I'm not sure. As always, this whole progression is somewhat moot if people aren't using a rescale, since then a Vanguard is capable of launching a Mun-orbital satellite...

My vote for the next thing to unlock would be the Juno/Jupiter - it's basically a shittier Thor, and has a less robust selection of parts associated with it. Atlas has to come ASAP due to Mercury...

**Comment by jsolson** [comment] 2016-11-29 19:58
My sense in a 3x playthrough (aborted at Atlas due to a Windows reinstall) is it moves very fast. You've basically got Thor/Atlas/Agena when your thinking about sending early Pioneer probes. I think I skipped Juno II entirely. My thinking with spreading out the advanced stuff in more branches is we can get some more breathing room early on. Vanguard to Atlas is a blur right now. It's not because our science is OP either, it's just the cheap early nodes.

Mercury-Atlas can wait. I got to it so fast I almost forgot to do Mercury-Redstone. If we can manage it I think it would be nice if the real rockets (Atlas/Titan) could start in tier 4 where it costs 45 science to unlock. Basic Thor would be ok one level sooner, just without Agena. It's quite capable and fun with a delta+small srb upper stage.

What do we have for advanced upper stages? Agena B/D, Vega, Centaur, Delta K, Transtage.

A big difference between Agena B and D besides the advanced engine was the mass. The D was very light. Balloon tank light.

**Comment by jsolson** [comment] 2016-11-29 23:53
Rough sketch stretching out the early stuff. Not too far of a departure from where we are, mostly a shift right. There's a disconnect between Agena A/B and the rest of the uppers, we just don't have room unless we co-opt another branch. Pretend there's a line from the Juno II S-3 and the S-I H1 and it almost looks historical. We should leave the Explorer and Pioneer 1 probes in start to give something to stick on top of a Vanguard. Does it make sense to include the Juno IV upper stages with the vacuum stages?

![](http://i.imgur.com/ZqBHPml.png)

**Comment by jmrd98** [comment] 2016-11-30 05:12
I'm going to try to get a 6.4x career started. My gamedata has gotten a bit bloated, although my free time is a bit compressed... (Sorry for the absences!)

Where would the small solid uppers fit into this? I'm never sure "when" is the right time to use them. Or, that 1.875 m vacuum solid, for that matter... Of course the name eludes me , d'oh!

**Comment by jsolson** [comment] 2016-11-30 09:00
>Where would the small solid uppers fit into this? I'm never sure "when" is the right time to use them. Or, that 1.875 m vacuum solid, for that matter... Of course the name eludes me , d'oh!

The 1.875m vacuum solid is the Castor 30. It tops the Castor 120s on Athena 1/2. They're in Heavy Rocketry now and I would say leave them there. Athena is modern, but in Ksp terms it's an easy to build 1.5m change of pace for 1 ton to LKO (great for polar orbit scansats). I think most of the booster srbs would be in Heavy/Heavier Rocketry, except for the very early and very advanced ones.

The small vacuum solids should all probably continue to appear early. Prior to Ablestar/Agena that's how it's done. Scout we might want to move to Start. It's basically a solid fueled Vanguard, and makes nice parts for a sounding rocket standin for those first suborbitals (I use a Vanguard engine on a long Able tank for that now).

There's still some tinkering to be done if we go this route. I'm curious what @minepagan thinks since he's put so much work into this.

Is this leaving room for any post Saturn V mega rockets that might be on the drawing board?

**Comment by CobaltWolf** [comment] 2016-11-30 14:41
Yeah, most of the vacuum solids are meant to come fairly early, with the exceptions of the STAR 37 and STAR 48, which can be placed wherever feels 'right' - ie, nodes where there aren't already upper stage solids! There's probably room for another, 1.25m pancake shaped one later on. 

I agree with Scout being in the starting node, or possibly basicRocketry.

**Comment by minepagan** [comment] 2016-12-01 14:05
The problem I have with that tree is that you don't get the Saturn until the same level that you get the NERVA....also, you get Titan-IV after it, despite it being comperable to something like the Saturn-1.
I am, however, likely going to rearrange the upper stages, and laterally rearrange some structural/fuel parts.

What I really need help with is the Delta parts, since I have never used them very much, so I don't know how they preform in game.

**Comment by CobaltWolf** [comment] 2016-12-01 15:01
@minepagan Delta II is basically the end of the 1.5m (and, honestly, 1.25m) lines - nothing better comes after it. Honestly, I think more or less where the Delta II first stage is right now is fine - a few nodes back from the end of the tree, leaving the last couple nodes to be big SHLVs etc. 

Titan-IV should come with Atlas V, whenever you get that.

@jsolson Honestly, I'd rather have the compression at the beginning (face it, a lot of stuff came online at the same time, with vastly similar capabilities) than have things like Agena coming halfway down the tech tree.

**Comment by minepagan** [comment] 2016-12-01 15:41
Have Titan-IV with Atlas-V? I'll see how that plays out.
Also, I remember you saying earlier that Delta-K was in the wrong spot? Where should it be?

**Comment by CobaltWolf** [comment] 2016-12-01 16:07
One of the two I circled here, ignore the text I just took it from higher up in this thread
http://i.imgur.com/cddkDYt.png

**Comment by jsolson** [comment] 2016-12-01 20:03
Strongly feel the 1.875 launchers should wait until tier 4. At tier 4 the nodes cost 45 and you're not unlocking several nodes with one explorer launch anymore. Saturn V could come tier 6. Assuming you are ok with using the branches parallel to the mainline rocket development there's room to juggle things.

Thor->Delta II is pretty much:
1. Thor (DM-18,19 etc). The short guy with the fins and long slanted tank.
2. Long Tank Thor, Thrust Assisted Thor (Castor)
3. Extended Long Tank Thor - for us that's long tank + short extension + RS27 engine. This step could be skipped.
4. Extra Extended Long Tank Thor (Delta/Delta II). That's the blue tanks. The Delta K appears here also. There's really the Delta 1000, 2000, 3000 and who knows what else before you get to the 7000 series which is what we know as Delta II.

At some point the GEM series boosters get introduced. They are Delta II parts, but multi purpose since we lack anything between them and the Castor. I'm not sure how soon they are needed. The heavy GEM motor might be a last tier thing.

A Titan III is Titan IV engines with Titan I/II tank parts and boosters added. There were so many variations it's hard to not lego up a replica by accident just throwing parts together. Titan III gets boosters up to the UA1207. Titan III could be spread out with some of the boosters being added with Titan II.

All of the needed Titan III parts, Delta II, and the 3rd Atlas Engine upgrade at the same tier level as Saturn V would be appropriate.

Titan IV has an A and a B version. A is the UA1207 booster, B is the USRM booster. So for us Titan IV means Titan IV tanks + USRM boosters. You could introduce the tanks with Titan III, and just save the USRM for later.

Atlas V is 2.5 meter (I think), but it is the most advanced LF/O engine in the game including stock stuff.

I don't like direct comparisons between Saturn and mass produced rockets since it is an early tech race to the moon monster that is hard to fit into a KSP progression. That's part of the reason I favor an alternate branch approach for that.

Agena D, Centaur, and probably Vega should be married.

**Comment by CobaltWolf** [comment] 2016-12-01 20:30
I disagree on Centaur. Developing high energy hydrolox upper stages like that is a pretty massive technical advancement over things like Agena and Vega. Remember that those were both supposed to by interim stages until centaur came online. 

-----Original Message-----

**Comment by jsolson** [comment] 2016-12-01 21:00
Centaur first launched in '62. It exploded when the insulation fell off, but it did exist. Agena D in '63. A few months later Centaur was successfully launched. Vega was cancelled in favor of the Air Force's Agena. We could separate them, but the three are tied. Agena D was the end point of a line of development, where Centaur was a beginning.

**Comment by jsolson** [comment] 2016-12-01 23:22
What about this?
![](http://i.imgur.com/0vAESPc.png)

**Comment by minepagan** [comment] 2016-12-02 01:16
Ehhhhhhh.....I don't really like putting engines in non-rocketry lines....other than SMs, of course. I'll take a look next chance I get.

**Comment by jsolson** [comment] 2016-12-09 23:13
So @minepagan have you decided how you are going to proceed on this? I'm planning on going through all the cfgs and updating mass and cost values. I can transcribe the tech tree nodes from the rebalance cfgs as I go.

**Comment by minepagan** [comment] 2016-12-10 00:16
When are you planning on that? I was going to do a pass today based on feesback and my experiences in a science save, but yeah you can transcribe the existing ones.

**Comment by jsolson** [comment] 2016-12-10 00:21
It will take me a week or two (or maybe a night if I'm really motivated). If you got changes coming I'll wait for them. No hurry.

**Comment by minepagan** [comment] 2016-12-10 00:57
On an unrelated note, while you're at it you might want to include the updated WBT

**Comment by minepagan** [comment] 2016-12-10 02:10
Alright, turns out I had my work cut out for me! Apparently some time in the past I'd already re-balanced most of the parts that needed it, all that was really left was Agena and a few miscellaneous parts. @jsolson you should be able to start integrating things directly into the CFGs after this, although I'd wait at least a week for feedback.

Also, on the topic of additional tech tree nodes: I'd suggest adding 4 nodes, in the following places:
15-pt rocketry node for Thor & Agena-A/B
45-pt rocketry node for upper stages, leading to Propulsion/fuel Systems
100-150(130?)-pt rocketry node between Propulsion Systems & Precision Propulsion (I plan on making this line the LH2 upper stage line if we do this)
300-pt rocketry node between Heavier Rocketry & Very Heavy Rocketry for early Saturn-V evolutions.
(Also, I'd suggest making the Precision Propulsion lead to the 300-pt node)

**Comment by jsolson** [comment] 2016-12-10 02:44
>Also, on the topic of additional tech tree nodes:

Whoa, that's an option?

**Comment by minepagan** [comment] 2016-12-10 02:54
I believe it had been descussed previously, to help relieve some of the compression in the tree.

I'd said "on the topic of" b/c I'd mentioned it in the PR

**Comment by jsolson** [comment] 2016-12-10 03:38
I'm ok with it. Do you know how to do it? And can it be made compatible Community Tech Tree? I believe that's the only one out there that extends rather than replaces the stock tree.

**Comment by jmrd98** [comment] 2016-12-10 06:17
I would have to look into the "how" of new nodes, but for making it compatible with CTT, that's something that a NEEDS:[BDB&!CTT] switch would do. I haven't looked at CTT in a while, maybe there are similar nodes to the aforementioned such that it would look much the same with or without the proposed changes?

**Comment by minepagan** [comment] 2016-12-10 13:02
Well I know the first 2 nodes would be fine, as the earliest CTT node is down near the science and CM lines, not the rocketry ones. I *think* the 3rd one would also be fine, but I have a feeling that the the 300-pt one may cause some problems.

**Comment by minepagan** [comment] 2016-12-14 17:05
Yo Jso (I can't tag on mobile) do you want me to work on changing the tech tree placement of

**Comment by jsolson** [comment] 2016-12-15 02:16
Go ahead. There's probably not much to do for ctt. Other than the extra command module nodes it all looks like beyond the end of the tech tree nodes.

**Comment by jsolson** [comment] 2017-01-14 05:00
I'm finally finished transcribing these changes.

Among other minor things I double checked all the tank dry masses and cost and fixed a lot of little errors. One Major error was the S1E tank. It [went from](https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4ac1b2372e85ae982ccf672fc635a653f7b0b30e#diff-9e569172814e68a3df456bfa5fa1de21L24) 6.25 tons to 9.375 tons, not a minor change. I'm tempted to suggest making it a balloon tank but I don't know if that would be appropriate.

**Comment by CobaltWolf** [comment] 2017-01-17 19:34
Well, one thing to keep in mind - the S-1E (Unlike most stages) is a common bulkhead design, like Atlas or Centaur. So you save the weight of one tank end and the associated interstage segment, and you get more utilization of a given cylindrical volume. It is not a balloon tank however. 

Actually, that's something to think about when it comes to Atlas/Centaur as well...

**Comment by jsolson** [comment] 2017-01-17 22:59
The S-IE full build dry mass is 5 tons lighter than the S-I, and it holds more fuel. Wet their mass is almost identical. And the S-IE has more thrust. So I think we're good, balance wise between them.

**Comment by jsolson** [comment] 2017-01-25 23:20
The Inon 1.875 fairing needs to be moved up to General Rocketry. That's a Vega part too.

**Comment by jsolson** [comment] 2017-02-11 04:28
Continuing my 3x playthrough...

The S-I stage arrives in Advanced Rocketry. But the S-IV is later in Heavy Rocketry. It's kind of useless without a second stage. Not even a p-fairing to rig something up.

Solar panel balance looks really good. They come earlier than stock (much needed) but don't track the sun yet.

**Comment by IronCretin** [comment] 2017-02-11 05:09
Use Titans for upper stages: https://en.wikipedia.org/wiki/Saturn_A-1

**Comment by jsolson** [comment] 2017-02-11 05:38
Ok, that works. We lack a 3.75m-1.875m adapter though. There's the S-IVB 3.75m fairing base, but that and the stock one are way far down the tree.

**Comment by CobaltWolf** [comment] 2017-02-11 18:23
Damn. I'll have to throw it in a to-do somewhere. I also sorta want to make the rest of the weird 'low energy' (as opposed to high energy hydrogen) upper stages but it's probably not worth it when there's much more desirable things to be made.

**Comment by minepagan** [comment] 2017-02-12 00:28
@jsolson there is a way to make an adapter at that tech level. Atop the S-1 tank, you need to put a 1.875m decoupler. Atop that goes the Titan's 1st stage engine - but put the Inon 1.875m fairing, upside-down, between the titan's engine and tank. Luckily, the Inon fairing's max diameter is 3.75m

**Comment by jmrd98** [comment] 2017-02-12 07:39
I'm doing (another) 6.4x play through, and there may be a hiccup with the early solids. The Thor type comes online in basic rocketry node, which feels good. There is the little "Dioscuri" SRB, as well as the stack and radial 'other' Dioscuri (I admit I don't know their real life names), the 0.625 m and 0.9375 m ones. The 0.9375 m radial is the one i'm scratching my head at, as following it in the next tier (General Rocketry) is the first of the "Delta" SRB, the "Ruby". It's smaller and more powerful than the previous larger model, even more so the 0.625 m. (It's also cheaper, which to me is a secondary balance issue, but it's still there.)

I imagine they're balanced properly, knowing how the backend works, I am more wondering at the gameplay aspect of the lower tier part. The window of usefulness seems very narrow. I see the rational for the inline models, they have their niche in light/All SRB booster models.

There might not be an answer, but I just wanted to throw it out there.

**Comment by jsolson** [comment] 2017-02-12 07:50
The strap ons need a look at. The old small Dioscuri and the new Castor are
the same thing, but very different sizes. Are you saying there are others
with obvious size/fuel discrepancies?

**Comment by jsolson** [comment] 2017-02-13 08:16
Following up on myself... We have the"Fenris-B Dioscuri" which is the strapon booster for Thor based on the Castor 1. It is correctly scaled and looks good on Thor. It is something around 0.5m.

We also have the new "Dioscuri-I" in stack and radial forms at 0.625m, which is the second stage of the Scout and is also based on the Castor 1. The problem is fitting Scout into 0.9375m and 0.625m parts makes it's scale >80%, rather than 64%-ish like everything else. When you take the radial version of the Scout Castor 1 and stick it on a Thor it looks ridiculous.

On the subject of fuel, initially when I did the solids I did them like the tanks: measured them and filled them to their volume. But when I compared those numbers to the real numbers it was a bunch of nonsense, unlike the tanks which lined up fairly well. What I did was disregard the visual model and fill them all to 19% fuel of whatever they are based on. That's why the old smaller Castor 1 and the new bigger one have the same performance.

So, what to do about it.

**Comment by CobaltWolf** [comment] 2017-02-13 15:00
We can just rescale the radial Scout-Castor in the config, maybe? The problem is I like the way the old SRB looked... :P

**Comment by CobaltWolf** [comment] 2017-02-13 15:02
Also, the Ruby being available so early was something of a concession. Perhaps push it back a bit?

**Comment by jsolson** [comment] 2017-02-13 20:52
>We can just rescale the radial Scout-Castor in the config, maybe? The problem is I like the way the old SRB looked... :P

You mean you like the old original Fenris-B Dioscuri/Castor 1? I like it too.

I'm unclear on why we would rescale the radial Scout-Castor. It's useful in the Castor 4 role, you can get 9 of them on a Thor ELT (aka Delta 39XX), and they look good. With this in place pushing the Ruby (GEM40) back would make sense.

I was really hoping the radial Scout-Algol could be made an AJ-60A for the Atlas V because it looks much better than the GEM60 on there but it's too small. It's more of a hypothetical GEM 55.

I'm fine with this Scout-XL btw. Gameplay wise it's more useful.

**Closed** 2018-01-30 20:17 UTC
Labels: balance, cfg, help wanted
