### ISSUE TITLE
Delta Dual Payload

### ISSUE THREAD

**Issue by McLeggy** [CobaltWolf/Bluedog-Design-Bureau#1510] opened 2024-07-25 02:06 UTC
The top part of the Delta Dual Payload Adapter is missing the inside node to attach to the bottom part when at extended length

**Comment by Rodg88** [comment] 2024-07-25 03:21
unable to reproduce, not sure what might be causing this. might need a log/configcache to see what's going on

**Comment by Rodg88** [comment] 2024-07-26 07:34
fixed by changing the node position switch to the top half, and fixed decouple direction

**Closed by Rodg88** 2024-07-26 07:34 UTC
