### ISSUE TITLE
Titan Touchups

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1464] opened 2024-06-29 17:22 UTC
- [x] Remove auto shrouds and convert to interstages. 

   Should be possible to make a new interstage part using the existing meshes and textures. Should retain the existing short variants for Lego purposes. 
      
- [x] #1465

  Should also be possible to merge the LR-87s and LR-91s. Could just reference in multiple .mu files and toggle them using the root transforms. Not sure if it’s within B9’s capabilities. 

- [x] Combine tanks variants for first and second stage where possible. 

- [x] tech upgrades to unlock tank variants

- [x] Combine length variants for UA-120s

- [x] Combine length variants for SRMU

- [x]  LR87 AJ11 12:1 and 15:1 ground/air lit variants with K models, remove AJ11A (replaced with optional patch with AJ9 etc)

- [x] Craft file updates - pending srmu nosecone

- [x] remove reference to `Titan2_FirstStageTank_NRM` in LR87 model, replacing with `bluedog_Titan2_FirstStageTank_NRM`

- [x] SRMU nosecone (maybe with 0.9375 top node variant, and possible motorless variant too)

**Comment by CobaltWolf** [comment] 2024-06-29 17:22
Formatting is so messed up will need to fix when I’m at a PC

**Comment by Rodg88** [comment] 2024-06-30 04:56
UA-120s may need new mu, just for plume scaling issues.

**Comment by Rodg88** [comment] 2024-06-30 05:31
The way the LR87s are currently set up for interstage use is just hiding the shrouds, and using the interstage node on the engine itself, on the subtype that includes the structural ring, since there's no engine mount par - the tank butts on the tanks themselves have the mount built in. This makes it pretty easy to attach an interstage too, as there won't be two similar nodes available at once, like when you have engine and interstage nodes together on an engine mount.

There's also a 'compact' mount option without the interstage node and structural ring, for use with engine mounts.

**Comment by JacobB094** [comment] 2024-06-30 21:44
Would refreshing the SOLTAN boosters be on the table? They're handy, but lack dedicated separation hardware and look much worse than UA series.

Another thing I'd love to see is an UA-series separation nosecone with nozzles rotated 90 degrees, like such: 
https://i.postimg.cc/0jMfVfhJ/screenshot374.png
It's ahistorical, but this configuration is necessary in most LDC configurations, as well as using those boosters on Saturn variants. This still provides sufficient clearance for separation, while avoiding the lower motors clipping into the core, or upper ones blasting it for that matter. In fact, this angle is not unlike SSRBs use. While it's a simple matter to rotate them, as shown in the pic, the raceways don't line up then, so if it could become a variant, my OCD could rest a little easier.

Also speaking of boosters, could we get Little Joe 2 variant of the Algol made into a radial solid booster, complete with a nosecone and a decoupler (perhaps it'd fit the Castor 1/2 one)? Titan 33BAS used a pair of Algols as boosters, but the current booster Algol is based on Scout one and thus drastically overscaled. Little Joe version is scaled more accurately, but has no nosecone variant nor surface attachment.

Another weird proposal: Titan-Vanguard. Basically, an entire Vanguard rocket riding on top of a Titan I lower stage. In practice, Vanguard engine is larger than 0.9375m, so I imagine this as simply a dedicated decoupler with a cutout for the vectoring nozzles (and probably hot staging vents, Vanguard was unreliable enough without trying to light it at low G), fitting its boattail's odd shape. For what it's worth, my cobbled together variant can get a small probe to orbit the Moon in KSRSS, just like what the real one was intended for.

Finally, a unitary 1.5m to 0.625m adapter would be helpful for Titan 1 ELV. Just a structural bit to mount an Able fairing on top. Maybe even just a variant of SOLTAN nosecone, seeing as it already has an option for a 0.9375m tip. 

I've been playing around with Titan a lot lately (as you might have noticed, not only with that), and these are the options for improvement I found. I'm holding off on (suggesting, not building, of course :) ) crazy stuff like Arcturus or Titan-Polaris, but these seem like minor extensions of the existing part list.

**Comment by Rodg88** [comment] 2024-07-01 09:23
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/8d6c8160-fd29-42f3-af71-b65cfe781a52)
The interstage could use the extra long version of titan 2 fairing from the LH2 vac model, maybe instead of the Titan 2 (Bare) variant which has texture stretching.

**Comment by CobaltWolf** [comment] 2024-07-01 18:32
@JacobB094 First off, we greatly appreciate the detailed feedback you've been leaving around here!

Now, responding to those points...
- I don't think I can make that nose cone variant due to how the part is unwrapped, but I'll take a loot.
- I don't remember how I did the Algols for Little Joe II. Chances are that part was never meant to be used outside that context, and is lacking details let alone texture space.
- Titan Vanguard, probably not going to do.
- As for adapters, I did kind of intend for the player to use the various other adapters from stuff like Thor for attaching upper stages to Titan 1. 

In general the stuff for early Titan variants is pretty thin and I'm not inclined to spend a lot of time on them. Plus I wasn't really intending on making new parts for this update - just reconfiguring the parts we already have.

**Comment by JacobB094** [comment] 2024-07-01 21:40
For Algols, the Little Joe ones actually look better, detail wise, than the Scout ones, by a fair margin at that. It's not a complex model anyway, white tube with a nozzle (there's even a canted option, would be great for this). If you can squeeze a nosecone in somewhere, or make a new part (there's conveniently placed node on top for attaching it to Little Joe), then enabling surface attachment would be all it needs.

I can see that Titan-Vanguard would probably work best as part of a wider Vanguard overhaul, however I don't think that's planned anytime soon. If there was a 0.9375m boattail of some sort, a Vega engine could be substituted (unless the shroud had vents that would accommodate the compact variant of the Vanguard version), but there are precious few parts in that size.

The thing with Thor is, there are no 1.5m to 0.625m adapters there, either. :) It's a large jump between unconventional sizes. Able is 0.625m, but the interstage only goes out to 0.9375m. I prefer having only a single structural part for this role because stacks of multiple low mass adapters tend to get wobbly. Admittedly, it's not a top concern for an Able shroud with a Star 20 inside, but you know how KSP joints are.

I get it that you're not really making new parts, however I saw that you were updating the Titan, and figured I could come up with a handful of structural pieces with QOL benefits. I enjoy making weird, unconventional proposals, so I tend to happen on such (in fact, there's a lot more than feedback coming your way soon, I just need to get my spreadsheet in order :) ).

**Comment by CobaltWolf** [comment] 2024-07-02 17:51
I'll take a look at the Algols then, I do love me some 3BAS2...

Vanguard is already pretty 'final' and isn't going to receive a revamp, likely ever. 

The lack of an adapter is something I can look into fixing. 

I've been asked and will look into making nose cones that match the SRMU nose.

**Comment by Rodg88** [comment] 2024-07-09 11:56
Some .mu file updates needed for the tank merge: bluedog_Titan2_S1_Lower_Tank needs a new parent transform (or just move the collider under `Titan2_LowerTank_Merged_polySurface75`), and bluedog_Titan3_S1_Stretched_Tank also needs a new parent transform. bluedog_Titan4_S1_Lower_Tank needs a unique mesh name too, it's also called Titan2_LowerTank_Merged_polySurface75 so confuses the part switch

**Comment by Rodg88** [comment] 2024-07-10 02:41
LR87 titan1/2 mount meshes use an old material that reference `Titan2_FirstStageTank_NRM` instead of `bluedog_Titan2_FirstStageTank_NRM`. Both textures are identical. Could remove the non-bluedog texture file if model is updated so the materials reference `bluedog_Titan2_FirstStageTank_NRM`

**Comment by JacobB094** [comment] 2024-07-10 22:27
Could we switch to using transformMultipliers on LR-91 variants, instead of multiple instances of ModuleEngines? It looks messy, with two fuel bars in the staging list, plus it makes it incompatible with RSE. It makes no sense to be able to run the turbopumps' gas generator, but not the pump itself.

Would be nice if this could be done to Vanguard and Vega GE-405s, as well. They still use that old method. I don't think anything else does.

**Comment by Rodg88** [comment] 2024-07-11 04:03
> Could we switch to using transformMultipliers on LR-91 variants, instead of multiple instances of ModuleEngines? It looks messy, with two fuel bars in the staging list. It makes no sense to be able to run the turbopumps' gas generator, but not the pump itself. I know it's a small thing, but it kind of bugs me.

I'm looking into this, as it would be better than dual engines I agree. However I'm not even sure the feature works, and all thrust transforms seem to get equal thrust. It kinda works still, but you get way more control authority than you should

**Comment by Rodg88** [comment] 2024-07-11 08:39
Pushed the transformMultipliers update, including hypergol/AJ11A patch updates.

Also @JacobB094 while a 90degree variant of the SRB nosecone isn't possible without new textures, I have added one without any separation motor at all, so you could manually place one.

**Comment by JacobB094** [comment] 2024-07-11 09:49
That'll be quite useful, too. I have another thing that could be done: could we get both variants of the mounting ring from LR-91 added to the fuel tank (moving the interstage node downwards if both are enabled)? The idea is to go from a tank-engine-interstage-tank stack and a tank-interstage-tank one, the way many other upper stages in BDB are done. The latter is much more stable. You can already do that, but you lose the mounting ring. I've been getting some problems with wobbling of Titan stacks, particularly SRM-based ones, due to high thrust at burnout. It would also decouple the style of the mounting ring from the engine config, which is I'd also like to see.

**Comment by Rodg88** [comment] 2024-07-11 10:33
It'd be a bit weird removing the mounting rings from the 4 vernier LR91s imo, but maybe. Do you use Kerbal Joint Reinforcement?

both GH405s have been updated too

**Comment by Rodg88** [comment] 2024-07-11 14:27
I can look into adding those basic rings to the tank to allow for neater interstage usage. KJR will completely fix those stability issues though, and I haven't had issues with it at all in the last few years, I always have it installed. 

I don't think any textures are going to be reworked just for deferred quite yet.

**Comment by JacobB094** [comment] 2024-07-11 15:35
It's not just for Deferred, that just makes it more obvious there's something amiss. The specular value is used by stock KSP shaders as well, and you can see subtle differences between texture "shinyness", especially on parts that are mounted together. Stock lighting sucks, so it's easy to ignore, but it's there. Compare Centaur D to older Centaur G parts, for example. With Deferred, the former is shiny and the latter is not, while in stock, the former looks just sort of newer and less dull, if that makes sense.

I believe it's not something that'd call for a full rework, either. Most of the texture is fine, it's just the specular map that's off. It's not even that it's not shiny, but that it's inconsistent. LDC parts, for example, are all fine, it's just parts of the most basic Titan configurations that are affected. It's almost as if some blue wolf had learned how to use the specular channel halfway through the last Titan rework... :)

**Comment by JacobB094** [comment] 2024-07-12 13:19
OK, I know it's out of scope, just leaving it here so it doesn't get lost. One Titan I ELV proposal was to use the second stage of Polaris missile as a kick motor, which would have made a capable LEO launcher (about 2.26T). While searching for data to approximate its performance, I found that it had a really interesting shape:
https://upload.wikimedia.org/wikipedia/commons/9/9c/Polaris_A3_ballistic_missile_upper_stages.jpg

It works out to 0.9375, which means a SOLTAN nosecone could be used as an adapter, or a bespoke top adapter looking more like the top of a Titan I missile could be made (BDB used to have this part back when it also had a Titan I RV). The motor came in two lengths, A1/A2, which was slightly shorter, and A3, as in the picture. It also had thrust termination ports in front. It would have probably been topped by a large shroud, seeing as it'd take quite a big sat (for the period) to hit over 2T that this thing could launch.

While BDB doesn't exactly suffer from a shortage of early tech solid kick motors, I really like the four nozzle design and the toroidal hydraulic tank.

**Comment by JacobB094** [comment] 2024-09-13 17:42
It's kind of late for that, but would that be possible to add Dynasoar LV wings at one point?
https://forum.nasaspaceflight.com/index.php?action=dlattach;topic=40012.0;attach=1330717;image
There are many concepts floating around, but this mockup seems to have forward swept trailing edges on the big ones, which you rarely see in artwork. There is a Dynasoar mod already, so it'd be nice to have the wings.

**Comment by JacobB094** [comment] 2024-09-30 11:02
Also, could we add an optional radial node to Titan lower stage tanks, so they're easy to attach to UA decouplers? That would make building Titan designs with LRBs easier.

**Comment by Rodg88** [comment] 2024-09-30 13:14
Not going to add it as standard, due to UI clutter, non standard use (meshes don't really fit together well), historical player confusion with LRB nodes, and the fact srf attach works pretty well in most cases (the decoupler has a collider along it's entire length for attaching to). But I am partial to a node attached booster, so have added it as an optional patch. No fancy node repositioning with tank variants, so offset tool is required.
But craft files made with the optional patch do *not* require the patch to be installed to load/work, the node attachment will still be present in the craft.

**Closed** 2024-09-30 13:14 UTC
Labels: Revamp
