### ISSUE TITLE
Compatibility file for UniversalStorage needs to be updated for UniversalStorage2

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#498] opened 2018-12-07 07:45 UTC
Effects 1 part, the Apollo Service Module.

**Comment by jmrd98** [comment] 2018-12-09 07:53
I will attempt to take a look at this in the coming days. I will have some free time hopefully as the holiday time nears.

**Comment by jmrd98** [comment] 2018-12-13 08:41
I have this mostly working, I think. The nodes had to be adjusted along with the MM needs, but I want to give it some more testing. It has turned into a bit of 'YMMV', though: It still works as intended, but the artistic style of US2 has made things a little less uniform than previous. (The art is awesome, I am stoked it's finally here.) The result is that some of the wedges seem to clip into each other depending on what combination is loaded. As this is just a bonus patch, I think that will be OK.

What would be cool as a stretch goal would be for the surprise I found in their custom sized Gemini bay+structure: I tried to weld some engines onto it, but it didn't take too kindly to that :D
@CobaltWolf: How hard on a scale from 0 to 'lolNO' would it be to supply the two monoprop motors from the gemini service module as a separate (surface mount) part(s)?

**Comment by jsolson** [comment] 2018-12-13 09:53
>How hard on a scale from 0 to 'lolNO' would it be to supply the two monoprop motors from the gemini service module as a separate (surface mount) part(s)?

The Place-Anywhere 7 Linear RCS Port with Fore by Throttle turned on. Two of them would be 4kN vs the 10 kN we put in the SM, but the real one was only 710N (I'm not sure if that's combined or each) so it's still OP.

**Comment by CobaltWolf** [comment] 2018-12-13 17:57
Honestly we might be justified in remaking the SMs for the Apollo and Gemini for a variety of reasons.

**Comment by jsolson** [comment] 2018-12-15 12:05
@jmrd98 I recently modified the service module in this commit. https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/a337aa3c33b1053c13389fad447fcbbc4f7275b1
Make sure you incorporate those changes. Sorry about that.

**Comment by jmrd98** [comment] 2018-12-21 05:44
Life got complicated for a bit, but between now and the new year I can get back to this. @jsolson, it's all good, I rebase whenever I pull anyway so it should all work out in the end.

**Comment by jmrd98** [comment] 2018-12-22 07:01
Huh. Didn't intend to close the issue, but hey, why not. This should be good to go in any case.

**Comment by jsolson** [comment] 2019-03-06 20:20
Forum post:

> Minor thing, but please could you add UniversalStorage2 (or just a * I suppose) to NEEDS[UniversalStorage] in US compatability cfg?  I've tested US2 wedges in the Kane Blk2 and it mostly fits just fine.  Only the water tank clips ever so slightly into the sliding panels but that can be tweaked into behaving itself properly with judicous use of the pointy arrows tool.

>Edit:  just seen the commit from Dec that tweaks the nodes slightly for US2, but for me the wedge brackets didn't show up until I edited the cfg to add a 2 in...

**Comment by jmrd98** [comment] 2019-03-06 20:37
That's a simple goof on my part, just add the 2 as required. 

"Complete" solution is to keep the old nodes for the depreciated version as a second section, but I don't have much interest in supporting depreciated mods.

**Closed** 2019-03-06 21:17 UTC
