### ISSUE TITLE
Kane-11 LIB EVA Floodlight not moving

### ISSUE THREAD

**Issue by Atomic-Thunder** [CobaltWolf/Bluedog-Design-Bureau#1042] opened 2021-03-13 08:37 UTC
As the title says the light is stationary and will not move when turned on.
![Screenshot (73)](https://user-images.githubusercontent.com/80572093/111024533-32cefa80-8444-11eb-834f-0f8b2ae92ef7.png)

**Comment by zorg2044** [comment] 2021-03-13 10:02
Is this with the current release? It should be fixed on the github master, will be included the next release. This was caused by KSP changing the light module.

**Comment by Atomic-Thunder** [comment] 2021-03-13 22:32
This is the current version available through CKAN.

**Closed** 2021-03-22 23:29 UTC
Labels: Next Release
