### ISSUE TITLE
Weird issue with X-405 Liquid Fuel Engine

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#492] opened 2018-11-30 22:01 UTC
The vessel slowly slips down on launchpad:

VAB:
https://i.imgur.com/SnD8DlN.png

Launch pad after loading:
https://i.imgur.com/RR6jtCB.png
Launch pad a minute later:
https://i.imgur.com/NHWuBYv.png

Video:
https://www.youtube.com/watch?v=rrn3RLldp6I

I use the latest dev from today.

**Comment by Gordon-Dry** [comment] 2018-11-30 22:05
Last session I had no issue and that was AFTER I updated KJR to
https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/releases/tag/RELEASE%2F3.4.0.0

**Comment by Gordon-Dry** [comment] 2018-11-30 22:12
btw the X-405 got a really huge 2nd node below it ...
https://i.imgur.com/E3pohOL.png

**Comment by jsolson** [comment] 2018-11-30 22:20
That extra node is added by Modular Launch Pads I think. Aren't you supposed to connect to that?

**Comment by Gordon-Dry** [comment] 2018-11-30 22:57
I tried both nodes.

**Comment by Lisias** [comment] 2018-11-30 23:08
I had this **exacly**  behavior using clamps and B9 cryogenics and TweakScale. By some reason, B9, TweakScale and a third add-on that I didn't identified to the moment causes a NRE when TweakScale is initializing itself, and that parts are rendered with ZEROEs in all his physics data.

When I leave the scenario running unattended for some time (I never chronometer it), statics started to explode on my game. This happens with you too?

Initially, I was thinking it was related to a race condition I had earlier (that I fixed by some delay loops on the initialization routine), so I as suggested that moving the initialization code to the SpaceCenter scene (from the current Main Menu) would solve the issue. It did not - it's another problem, with another root cause.

Could you publish the .craft file, Gordon? This would make my testings easier.

**Comment by Gordon-Dry** [comment] 2018-12-01 00:16
I try it again without Modular Launch Pads (because it adds the extra node to engines) and latest KJR.

^btw the issue also occured with stock launch clamps or launch clamps from other mods.

**Comment by Lisias** [comment] 2018-12-01 00:52
This probably can be fixed on a exempt from KJR's config.xml.

I'm opening an issue there, so you do not pollute this add-on with something that could be handled by KJR.

https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement/issues/4

**Closed** 2018-12-01 01:08 UTC
