### ISSUE TITLE
Early probe cores don't have enough EC

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#187] opened 2016-10-01 19:14 UTC
The early game, pre-solar-panel probes like the Sienno, Ramo, and Amba Barely hve enough EC on board to transmit even one of their built-in experiments, and they usually have two or three. And even if I had panels, I dont really want to use them because it breaks the realism.

**Comment by jsolson** [comment] 2016-10-01 21:34
The thing to check before we start throwing EC in is are the transmitters OP for the mission. Twice the range is 4 times the power, so cutting range will save a lot of juice.

**Comment by IronCretin** [comment] 2016-10-01 21:35
Less transmission cost could work too for balancing.

**Comment by jsolson** [comment] 2016-10-01 23:27
What I'm getting at is we can't just put whatever numbers we want in there, we want to stay balanced with stock, and the answer is not always Moar EC. The Sienno for example has an antenna thats equal to the Communotron 16 (the baseline stock omni antenna). With it's 500Km range, against a level 1 DSN it has a range of  31.6 Mm and a packet resource cost of 12.

Cut the range in half and you cut the power 4 times. A 250Km antenna against a level 1 DSN has a range of 22Mm and a packet resource cost of 3.

Cut it in half again, the 125Km antenna against a level 1 DSN has a range of 15Mm and a packet resource cost of 0.75.

15Mm is still out past the Mun, so cut it in half again.  A 62.5Km antenna against a level 1 DSN has a range of 11.2Mm and a packet resource cost of 0.1875. That's within the mission requirements for this probe. The energy cost is 0.3 per sec instead of 20 per second, at exactly the same bandwidth.

**Comment by CobaltWolf** [comment] 2016-10-02 02:57
jeez dude that sounds like we might be able to balance these suckers

**Comment by jsolson** [comment] 2016-10-04 10:09
I've re-thunk the above. Since range is only meaningful when there's a receiver, and the formula for range is sqrt(ant1 range * ant 2 range) reducing one of the antennas range 4x reduces the effective range in half. So range would scale linearly with EC usage. That means the Sienno in the above example would use 2.5 EC per second, not 0.3.

**Comment by IronCretin** [comment] 2016-10-05 01:38
Relevant thread:
http://forum.kerbalspaceprogram.com/index.php?/topic/149131-electric-charge-for-science-transmission/

**Comment by jsolson** [comment] 2016-10-05 01:45
Been following that. That's why I say were in wait and see what Squad does
mode. I'm in agreement with the position that the problem is the
experiments, not the transmitters. We should probably check our own in
house experiments (are there any?) and make sure they don't demand
excessive bandwidth.

**Comment by CobaltWolf** [comment] 2016-11-11 16:18
how do we feel about this now that Kerbnet is in?

**Comment by jsolson** [comment] 2016-11-11 23:23
> how do we feel about this now that Kerbnet is in?

Is Kerbnet that map window thing? Not sure what you're asking.

**Comment by CobaltWolf** [comment] 2016-11-12 17:26
I thought Kerbnet was the name for the whole stock communications system.

**Comment by jsolson** [comment] 2016-11-12 23:58
I believe the last strategy for omni's was to start with a Communitron 16 and scale the bandwidth and range linearly with the ec consumption. So half the packetResourceCost (EC) gets you half the antennaPower (range) and twice the packetInterval (halving bandwidth). It seems to fit the abtracted system we have.

For dishes it's just what looks right since I couldn't find any formula to approximate what squad did. I think the general approach was to sacrifice bandwidth for range when one of our dishes needed the range of a much larger squad dish. Relays were only given to dishes that had a mission calling for it (Apollo). Last I checked a relay implies additional store and forward hardware, and the dish is 10x heavier then it would be otherwise.

**Comment by CobaltWolf** [comment] 2016-11-13 02:59
Those are some heavy relays. The next question, then - what does an early tier probe mission look like in terms of energy consumption? For the Pioneers in particular. Can they make it to the Mun and transmit an experiment? Minmus? Do they work with longer travel times in 64k or whatever? They may need patches to lower their consumption. 

I want to make them both single experiment as well. Geiger for pioneer 1, the camera for pioneer 3. I know you're pulled in a lot of directions but remind me where/if we landed with the camera stuff?

Perhaps make Pioneer 1 have lower bandwidth and higher range than Explorer 1? Making it different, along with the (honestly) more useful shape. 

-----Original Message-----

**Comment by jsolson** [comment] 2016-11-13 06:09
We have hibernation on probes remember.

**Comment by jsolson** [comment] 2016-11-13 15:20
>The next question, then - what does an early tier probe mission look like in terms of energy consumption? For the Pioneers in particular. Can they make it to the Mun and transmit an experiment? Minmus? Do they work with longer travel times in 64k or whatever? They may need patches to lower their consumption.

I did look at their missions when setting up the ranges, but another look is probably needed. We are religiously stockalike, so a patch to stock antennas for 64k ranges would work on ours as well. I don't know if it's occurred to anyone to do this yet with antenna ranges being a new thing. For all I know there's a global antenna range modifier.

>remind me where/if we landed with the camera stuff?

Nowhere different.

**Comment by CobaltWolf** [comment] 2016-11-13 18:52
I forgot that there is a hibernation feature now.

**Comment by jsolson** [comment] 2016-11-14 12:32
Assuming liberal use of hibernate... Explorer is good for a few experiments transmissions from Kerbin orbit. Pioneer nearly drains the battery with just one from Mun. The problem there is the higher science return from the Mun vs Kerbin is a higher transmission cost. They both have the same EC.

Save me some time here, what should the probes be capable of?

We can probably give the Mun probes very low bandwidth in exchange for lower ec cost without making uber antennas. Anything going farther out without some way to generate power is in trouble.

**Comment by CobaltWolf** [comment] 2016-11-14 12:36
IRL anything past the Moon ( and most things going to it) had solar power, so these little guys are a bit of a special case. The transmission cost scales with data value? That's... Idk. It might make sense but right now it makes our lives harder. 

Pioneers should be good to the Mun (+ Minmus?) and then transmit once. 

-----Original Message-----

**Comment by CobaltWolf** [comment] 2016-11-14 16:09
that commit looks good @jsolson I'll have to play with it in game.

**Closed** 2016-12-04 22:58 UTC
Labels: balance, cfg
