### ISSUE TITLE
Kerbalism or Kopernicus -B9partswitch errors on solar panels

### ISSUE THREAD

**Issue by AnonymousJedi** [CobaltWolf/Bluedog-Design-Bureau#977] opened 2020-10-22 15:56 UTC
My B9partSwitch is not working correctly with BDB, do you have any idea why?
![Screenshot 2020-10-22 094824](https://user-images.githubusercontent.com/73246703/96898257-c0d22680-144c-11eb-8891-4d83906cac96.png)

**Comment by Clamp-o-Tron** [comment] 2020-10-22 16:25
I've run into this before, I can't remember how I fixed it. Maybe a reinstall or deleting the MM cache?

**Comment by AnonymousJedi** [comment] 2020-10-22 17:33
i found out that you need to update ksp to the newest version

**Comment by AnonymousJedi** [comment] 2020-10-22 17:33
i just degraded my BDB to 1.6.3 for the meantime while i update ksp to its newest version

**Comment by zorg2044** [comment] 2020-10-22 20:27
@AnonymousJedi unfortunately this appears to be caused by the way ``some`` versions of Kopernicus handles solar panels. The current BDB release works properly with the latest builds of Kopernicus and should be fine in future versions. We are trying to find out what the problematic versions are, can you let us know which version exactly you were using?

Also I believe the solar panels above should be fine, the switch in power between variants wont work but I think they will be functional.

**Comment by AnonymousJedi** [comment] 2020-10-22 20:47
im using 1.10

**Comment by AnonymousJedi** [comment] 2020-10-22 20:47
but also
![Screenshot 2020-10-22 100129](https://user-images.githubusercontent.com/73246703/96928282-92b50c80-1475-11eb-9dd4-1e34a0093822.png)

**Comment by AnonymousJedi** [comment] 2020-10-22 20:48
may this be a problem?

**Comment by zorg2044** [comment] 2020-10-22 21:35
I think we might need your KSP.log to see whats going on. As well as your modulemanager.configcache

**Comment by AnonymousJedi** [comment] 2020-10-22 21:35
where is that

**Comment by AnonymousJedi** [comment] 2020-10-22 21:43
i dont know how to send those

**Comment by zorg2044** [comment] 2020-10-23 21:23
@AnonymousJedi did you have Kerbalism installed?

**Comment by AnonymousJedi** [comment] 2020-10-23 21:34
yes

**Comment by zorg2044** [comment] 2020-10-23 22:23
This appears to be a conflict with Kerbalism, we are now looking into it.

**Comment by jsolson** [comment] 2020-10-23 22:57
With Kerbalism `SolarPanelFixer` and `Reliability` are added.

~~~
UrlConfig
{
	parentUrl = Bluedog_DB/Parts/ProbeExpansion/OAO/bluedog_OAO_solarUpper.cfg
	PART
	{
		name = bluedog_OAO_solarUpper
		module = Part
		author = Zorg
		rescaleFactor = 1
		node_attach = 0.0, 0.0, 0, 0.0, 0.0, 1.0
		TechRequired = spaceExploration
		entryCost = 6000
		cost = 2750
		category = Electrical
		subcategory = 0
		title = AOO-BSP-U Upper Solar Panel
		manufacturer = Bluedog Design Bureau
		description = Folding fixed solar panel for the AOO series of space obvervatories. <#CD7600> AUTHOR'S NOTE:  Attach in mirror symmetry to the sides of the AOO-WPE "Marquette" unit. A cut out on the corner of the panel allows for some overlap with the lower solar panel set. </color>
		attachRules = 0,1,0,0,1
		mass = 0.06
		dragModelType = default
		maximum_drag = 0.2
		minimum_drag = 0.2
		angularDrag = 1
		crashTolerance = 8
		maxTemp = 1200
		thermalMassModifier = 2.0
		emissiveConstant = 0.95
		heatConductivity = 0.04
		bulkheadProfiles = srf
		tags = deploy OAO AOO solar panel
		techtag = OAO
		MODEL
		{
			model = Bluedog_DB/Parts/ProbeExpansion/OAO/bluedog_OAO_solarUpper
		}
		MODULE
		{
			name = ModuleDeployableSolarPanel
			animationName = deploy
			raycastTransformName = USsunCatcher
			sunTracking = false
			pivotName = USsunCatcher
			isbreakable = true
			retractable = false
			OUTPUT_RESOURCE
			{
				name = ElectricCharge
				rate = 3
			}
			powerCurve
			{
				key = 206000000000 0 0 0
				key = 13599840256 1 0 0
				key = 68773560320 0.5 0 0
				key = 0 10 0 0
			}
		}
		MODULE
		{
			name = ModuleBdbSymmetricalPart
			transformNameA = UpperSolarLeft
			transformNameB = UpperSolarRight
			raycastTransformNameA = USsunCatcher
			raycastTransformNameB = USsunCatcher2
			pivotNameA = USsunCatcher
			pivotNameB = USsunCatcher2
			toggleSideEventGUINameA = Right Side
			toggleSideEventGUINameB = Left Side
		}
		MODULE
		{
			name = ModuleB9PartSwitch
			moduleID = meshSwitchSupport
			switcherDescription = Support Style
			switcherDescriptionPlural = Support Styles
			affectDragCubes = False
			affectFARVoxels = False
			uiGroupName = partSwitch
			uiGroupDisplayName = Part Switch
			SUBTYPE
			{
				name = Support
				title = Support On
				transform = USL_Support
				transform = USR_Support
			}
			SUBTYPE
			{
				name = NoSupport
				title = Support Off
			}
		}
		MODULE
		{
			name = ModuleB9PartSwitch
			moduleID = meshSwitchExtension
			switcherDescription = Extension
			switcherDescriptionPlural = Extentions
			affectDragCubes = False
			affectFARVoxels = False
			uiGroupName = partSwitch
			uiGroupDisplayName = Part Switch
			SUBTYPE
			{
				name = Angled
				transform = USR_extensionPivotAngled
				transform = USL_extensionPivotAngled
			}
			SUBTYPE
			{
				name = OAO1
				addedMass = -0.0025
				MODULE
				{
					IDENTIFIER
					{
						name = *SolarPanel*
					}
					DATA
					{
						OUTPUT_RESOURCE
						{
							name = ElectricCharge
							rate = 2.5
						}
					}
				}
			}
			SUBTYPE
			{
				name = Straight
				transform = USR_extensionPivotStraight
				transform = USL_extensionPivotStraight
			}
		}
		MODULE
		{
			name = SolarPanelFixer
			OUTPUT_RESOURCE
			{
				name = ElectricCharge
				rate = 3
			}
		}
		MODULE
		{
			name = Reliability
			type = SolarPanelFixer
			title = Solar Panel
			redundancy = Power Generation
			repair = true
			mtbf = 36288000
			extra_cost = 2.5
			extra_mass = 1.0
			rated_radiation = 0.15
			radiation_decay_rate = 1
		}
		MODULE
		{
			name = ModuleB9PartInfo
		}
	}
}
~~~

**Comment by hemeac** [comment] 2020-10-31 09:54
One solution may be to add a custom variable to all ModuleDeployableSolarPanel in which you are using a B9 transform on

For example you could have:
```
MODULE
	{
		name = ModuleDeployableSolarPanel
		animationName = deploy
		raycastTransformName = USsunCatcher
		sunTracking = false
		pivotName = USsunCatcher
		isbreakable = true
		retractable = false
		//resourceName = ElectricCharge
		//chargeRate = 16
		bdb = true

		OUTPUT_RESOURCE
		{
			name = ElectricCharge
			rate = 3
		}

		powerCurve
		{
			key = 206000000000 0 0 0
			key = 13599840256 1 0 0
			key = 68773560320 0.5 0 0
			key = 0 10 0 0
		}
	}
```
And then for the ModuleB9PartSwitch:
```
MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = meshSwitchExtension
		switcherDescription = Extension
		switcherDescriptionPlural = Extentions
		affectDragCubes = False
		affectFARVoxels = False
		SUBTYPE
		{
			name = Angled
			transform = USR_extensionPivotAngled
			transform = USL_extensionPivotAngled
		}
		SUBTYPE
		{
			name = OAO1
			addedMass = -0.0025

			MODULE
			{
				IDENTIFIER
				{
				name = *SolarPanel*
				bdb = true
				}
				DATA
				{
					OUTPUT_RESOURCE
					{
							name = ElectricCharge
							rate = 2.5
					}
				}
			}
		}
		SUBTYPE
		{
			name = Straight
			transform = USR_extensionPivotStraight
			transform = USL_extensionPivotStraight
		}
	}
```
B9 should then has two conditions that need to be satisfied.  That should fix the issue with the B9 also matching with the Kerbalism Solar Panel fixer. Or if you don't want to use a new variable, just choose another variable within the ModuleDeployableSolarPanel that is not present within another module that has SolarPanel

**Comment by zorg2044** [comment] 2021-03-04 21:41
This issue seems resolved with the latest version of Kopernicus and Kerbalism.

**Closed** 2021-03-22 23:29 UTC
Labels: Next Release
