### ISSUE TITLE
REVAMP: Agena Parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#583] opened 2019-08-05 14:13 UTC
The Materials Bay is fine as is.

ENGINES
- [x] 8048
- [x] 8081
- [x] 8096
- [x] 8096B
- [x] 8096C

COMMON
- [x] Avionics Core
- [x] Engine Mount (needs textures to be finished)
- [x] Straight Interstage

AGENA A / B
- [x] Short Tank
- [x] A Interstage
- [x] Engine Shroud (needs textures to be finished)
- [x] Ullage motor (needs textures to be finished)

AGENA D
- [x] Long Tank
- [x] Equipment Rack (needs textures to be finished)
- [x] Mesh switch for Equipment rack for Subsatellite/surface attachable equipment etc

SUBSATS
- [ ] Subsat decoupler
- [ ] P-11 subsat
- [ ] Vampan subsat
- [ ] Some third design?

FAIRINGS
- [x] Lunar Orbiter
- [x] Lunar Orbiter adapter
- [x] Poppy
- [x] Ranger
- [ ] Samos

AGENA TARGET VEHICLE
- [x] Long Tank Variant
- [x] Docking Port (will include a bunch of nice new details)
- [x] Secondary Propulsion System
- [x] Secondary Propulsion System (dual RCS)
- [x] Secondary Propulsion System (dual LFO)
- [x] Materials Bay (retexture)
- [x] Dipole antenna
- [x] Spiral antenna
- [x] Acquisition Lights
- [x] Running Lights
- [x] ATDA Battery
- [x] ATDA VHF Antenna
- [x] ATDA RCS
- [x] Nose cone
- [x] MM Detector Package
- [x] Nuclear Emulsion Package

CORONA POD:
- [x] Deorbit SRB/Adapter
- [x] Capsule
- [x] Parachute
- [x] Forward heatshield
- [x] Adapter
- [x] Double-return bucket adapter

KEYHOLE:
- [x] KH-1 Camera
- [x] KH-4 Camera
- [x] KH-4B Camera
- [x] KH-7 Camera
- [x] KH-7 OCV
- [x] KH-8 Camera
- [ ] KH-8 Solar Panels

KH-9 Hexagon:
- [x] Service module
- [x] Launch adapter
- [x] Service Engine
- [x] Fairing base
- [x] Camera System
- [x] Prime RCS
- [x] Lifeboat RCS
- [x] Adapter Truss
- [x] SRV Truss
- [x] Mapping Camera
- [x] VHF Antenna
- [x] Solar Panels
- [x] Mk8 SRV Heatshield
- [x] Mk8 SRV Pod
- [x] Mk8 SRV Parachute
- [x] Mk8 SRV Retro Pack

MISC PARTS
- [x] Multiple Spacecraft Adapter
- [ ] Mariner Decoupler
- [ ] Bespoke Drop Tanks
- [x] Biosat adapter
- [x] Biosat antenna
- [x] Biosat magnetometer
- [x] Retro Thrust Adapter

STRUCTURAL 
- [x] Titan 3B Adapter
- [x] Carrack straight adapter
- [x] Carrack wide adapter
- [x] Carrack interstage

**Comment by Pappystein** [comment] 2020-02-21 07:50
I have been experimenting with my personal Fuel Switcher using variables.   I created a Variable isAgenaTank and assign it at the start to all agena Tanks.   Then I use a patch similar to the Stock BDB fuel patch to patch just isAgeanTank = True to my Agena tankage.  Then my Agena tanks have unique fuel switching seperate from other tanks...

I would suggest the Stock BDB fuel switcher be converted to allow for similar peformance.   That way if a tank is a Balloon tank it could have the variable isBalloonTank.   A monococue tank (Agena and DCSS) could have isMonococueTank.   and the end result is your fuel switcher is simpler (you don't have to have a long string of names in a switcher section.)  You just look for the correct variable(s).

A second variable can/could be used to prioritize the FIRST choice for fuel type for each tank.
defaultFuelHydrolox
defaultFuelHypergolic
defaultFuelLFO
etc

I mention this here as  follow up to my previous point about the Agena tanks being somewhere between balloon and standard tanks.

**Comment by Pappystein** [comment] 2020-03-12 21:40
Two things:
I think the list is complete as outlined.  It would be nice if we had White/Green alt textures for the GATV battery but not important.

1) Source for 8096C looks like the 1981AAIA paper which has incorrect information.  It is actually quoting data for a proposed 8096L derivative.   8096C should have same thrust as 8096B but higher ISP.   

2) 0.9375 Straight Inter-stage (for Agena) tends to lock onto Agena if anything is put on the Agena-D Engine mounted Rack.   Game acts like the mass is there but the 8096 Engine can fire through as if the mass (and previous stage) isn't there.    I have tried several battery and Solar Panel combos from BDB as well as RESTOCK/RESTOCK+/Coatl.   I have not tested with SPS at time of post.

**Comment by CobaltWolf** [comment] 2020-03-13 14:32
8096C is based on the "Growth Agena" paper. I don't have it with me right now.

**Comment by Pappystein** [comment] 2020-03-13 22:52
Yes that is the document I am referring to.  except I mis-rememberd the year.  It was from 1987...

I guess, given my re-read of the document...   Can we get an Engine upgrade for this engine back to 16klb/f thrust at an increased cost?   I flew a "growth Agena" yesterday and while I was able to orbit the target planet without slingshots.   Burns were close to 20+ minutes long at 12klb/f      Anything to reduce the tedium would be appreciated (I am even willing to pay 2x the cost)   Photos to be posted today.

**Comment by Morphisor244** [comment] 2020-05-16 13:09
Hey there, I was flying some KH-1 stuff and found I was unable to get the return capsule to actually return without blowing up. Discussed this with @zorg2044 on discord, did some further testing afterwards, he recommended @jsolson have a look it.
Check out the screenshots: https://imgur.com/a/nbDROol

I'm using normal 100% re-entry heating and no other mods that affect heating.
I tried both a gentle high altitude entry and a ballistic reentry profile, as shown in the screenshots. In all cases and varieties I cannot prevent the capsule from overheating.
What strikes me as most interesting, is that the heat shield IS losing ablator, but it's not actually the hottest part on the craft - the capsule right underneath it is overheating as if it wasn't shielded.

**Comment by jsolson** [comment] 2020-05-16 13:56
Yeah I'm playing with heating right now and I noticed that the pod heats up faster than the heatshield. I thought I broke something but if you're seeing it... I haven't uploaded any changes so wtf.

I'll look into it.

**Comment by jsolson** [comment] 2020-05-19 06:51
@Morphisor244 try it again. I'm setting the command pod to be shielded when the heatshield is attached since the heatshield wasn't always protecting it from the airstream (too close tolerance on these parts I think). Note the retro pack should be jettisoned before hitting the atmosphere. Just wait for the chute to auto deploy and then drop the heatshield.

**Comment by Morphisor244** [comment] 2020-05-21 13:02
@jsolson Just flew a perfectly successful Discoverer mission, the adjustments seem to work as intended! Thanks for your efforts, on this and elsewhere.

**Closed** 2021-03-05 14:47 UTC
Labels: New Parts, Revamp
