### ISSUE TITLE
b9 part switch fatal error

### ISSUE THREAD

**Issue by qwertyuidfg** [CobaltWolf/Bluedog-Design-Bureau#1412] opened 2024-03-23 07:47 UTC
does anyone have any idea on how to fix this without removing bluedog design bereau?

![image_2024-03-23_174620501](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/164473589/c92a57eb-6e7b-4a94-bec4-e4935b5ca45c)

mod list: KSP: 1.12.5 (Win64) - Unity: 2019.4.18f1 - OS: Windows 10  (10.0.0) 64bit
ClickThroughBlocker - 2.1.10.21
Filter Extensions - 3.2.9
Harmony - 2.2.1
KSPBurst - 1.5.5.1
Toolbar - 1.8.1.1
ToolbarControl - 0.1.9.11
CommunityPartsTitles - 0.9.3
KSP-Recall - 0.4.0.1
Advanced Jet Engine - 2.20
Animated Decouplers - 1.5
ASET Consolidated Agency - 2.0.2
ASET Consolidated Avionics Pack - 3.0.1
ASET Consolidated Props Pack - 2.0.7
Astrogator - 1.0
B9 Part Switch - 2.20
BD Animation Modules - 0.6.7.1
Benjee10_MMSEV - 1.0.2
Plume Party - 0.5
Benjee10_sharedAssets - 0.2.2
BetterTimeWarpContinued - 2.3.13
Bluedog Design Bureau - 1.13
CameraController Next - 1.0.4
CameraTools - 1.34
Community Category Kit - 0.1.0.112
CommunityTechTree - 3.4.4
ConformalDecals - 0.2.12.100000
Connected Living Space - 2.0.2
Crowd Sourced Science - 6.1
CryoEngines - 2.0.6
CryoTanks - 1.6.5
Community Terrain Texture Pack - 1.0.5
CustomPrelaunchChecks - 1.8.1.1
DeployableEngines - 1.3.1
DepthMask - 1.1.3
DockingCamKURS - 1.3.8.7
DockingFunctions - 1.0.4
DynamicBatteryStorage - 2.2.5
Environmental Visual Enhancements - Redux - 1.11.7.1
ExtraplanetaryLaunchpads - 6.99.3
FarFutureTechnologies - 1.2
Ferram Aerospace Research - 0.16.1.2
FillItUp - 0.2.0.4
Firespitter - 7.17
FreeIva - 0.2.18.4
FShangarExtender - 3.6.0.2
HabTechProps - 0.2
HeatControl - 0.6.1
HideEmptyTechTreeNodes - 1.3.2
htRobotics - 1.0
Infernal Robotics Next - ConnectionSystem - 1.0.5
RasterPropMonitor - 0.31.13.4
KAS - 1.12.8285.34332
KerbalChangelog - 1.4.2
Kerbal Joint Reinforcement - 3.7.3
KerbalKonstructs - 1.8.6.1
Kerbal Reusability Expansion - 2.9.3
HyperEdit - 1.5.8
Kerbal Inventory System - 1.29.8039.40483
Kopernicus - 1.12.1.198
KSC Switcher - 2.1
KSP-AVC Plugin - 1.4.1.9
KSPCommunityFixes - 1.34.1
KSPWheel - 0.16.14.33
Infernal Robotics - 3.1.17
ModularFlightIntegrator - 1.2.10
Docking Port Alignment Indicator - 6.10
NearFutureAeronautics - 2.1.1
NearFutureConstruction - 1.3.1
NearFutureElectrical - 1.2.3
NearFutureExploration - 1.1.2
NearFutureLaunchVehicles - 2.2
NearFutureProps - 0.7.1
NearFuturePropulsion - 1.3.5
NearFutureSolar - 1.3.2
NearFutureSpacecraft - 1.4.3
PatchManager - 0.0.17.6
Kerbal Planetary Base Systems - 1.6.16
PlanetShine - 0.2.6.6
Airline Kuisine - 0.5
Procedural Fairings - 6.5
Procedural Parts - 2.5.8
RealChute - 1.4.8.3
RealFuels - 15.8.3
Real Heat - 5.1
ReStock - 1.4.3
RSS-CanaveralHD - 1.0.1
RSSVE - 2.1.6
Shabby - 0.3
Benjee10_sharedAssets - 0.2.1
HabTechProps - 0.2
Waterfall - 0.6.1
SolverEngines - 3.14
SpaceDust - 0.4.4
ButtonManager - 1.0.1.1
SpaceTuxLibrary - 0.0.8.5
VesselModuleSave - 1.0.1.2
StationPartsExpansionRedux - 2.0.10
SystemHeat - 0.6
Trajectories - 2.4.5.3
TexturesUnlimitedFX - 1.0.7.1
Tundra Exploration - 7.0
Tundra Technologies - 7.0
TweakScale - 2.4.7.6
TweakScale Companion (The ÜberPaket) - 2024.2.20
TweakScale Companion for AirCrafts - 1.0
TweakScale Companion for Airplane Plus - 0.1
TweakScale Companion for Frameworks - 0.4.0.3
TweakScale Companion for Firespitter - 1.3
TweakScale Companion for Kerbal Inventory & Attachment System (KIAS) - 1.1
TweakScale Companion Living Style - 0.0.3
TweakScale Companion Multipass - 0.1
TweakScale Companion for Neist Airliner Parts - 0.0.1
TweakScale Companion for Orbit Portal Technologies (OPT) - 0.0.1.1
TweakScale Companion for Post Kerbin Mining Corporation Add'Ons - 2.2.1.1
TweakScale Companion for ReStockPlus - 1.1
TweakScale Companion Rockets - 0.0.2
TweakScale Companion for SMCE - 0.0.2
Universal Storage 2 - 4.0.1.1
Waterfall - 0.9
Waypoint Manager - 2.8.4.2
WernherChecker - 0.5.13.1
Kerbal Actuators - 1.8.5
ZeroMiniAVC - 1.1.3.2
[x] Science! - 6.0.2
i also have Real solar system, realism overhaul, realistic progression, RO capsules, library, engines, solar, tanks and utils.

**Comment by Rodg88** [comment] 2024-03-23 09:09
Would at least need a full copy of the ksp.log to look into this. Did you install manually? Using CKAN instead can avoid a lot of issues, like multiple copies of waterfall being installed at once, or missing dependencies.

**Comment by qwertyuidfg** [comment] 2024-03-23 09:58
firstly, no i did not install BDB manually and secondly i got it to where the it only says the thing about BDB supply

this is the only useful thing in the console logs:  NullReferenceException: Object reference not set to an instance of an object
	scatterer.Utils.FixSunsCoronaRenderQueue () (at <684aa87c0d2345f8a9e4739403f4afff>:0)
	scatterer.Scatterer.Init () (at <684aa87c0d2345f8a9e4739403f4afff>:0)
	scatterer.Scatterer+<DelayedInit>d__35.MoveNext () (at <684aa87c0d2345f8a9e4739403f4afff>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
(i think this is the right log)

**Comment by Rodg88** [comment] 2024-03-23 11:22
That error is just related to scatterer so is unlikely to be the cause. Theres a lot more vital information throughout the log, including clues about why a patch might fail. From the mod list you posted it might be as simple as missing Community Resource Pack, one of BDB's dependencies, or it could be some other mod triggering a patch incorrectly, or it's to do with RO itself in which case we can't really offer support on our side.

The KSP.log I mention is the one in the main ksp folder, zipping it is recommended to make it much smaller to upload as it can be quite large.

**Comment by qwertyuidfg** [comment] 2024-03-24 03:25
turns out the problem was that a few dependencies were not actually installed by CKAN, anyways now the only problem is that i cant load into a game without it deleting all my craft and crashing my game.

 log file: 
[ksp log.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/14734253/ksp.log.zip)

(thanks for the previous support!)

**Comment by qwertyuidfg** [comment] 2024-03-24 03:30
use this log file instead because this one has the info of what happened after i loaded a save: 
[betterlog.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/14734262/betterlog.zip)

**Comment by Rodg88** [comment] 2024-03-24 04:38
You have two different system changing planet packs, RSS and Other Worlds, not likely to be compatible. I'd also recommend uninstalling that version of tweakscale (and ksp recall/tweakscale companion) and use TS Rescaled instead as it will have less bugs, should be able to switch to this version without breaking any craft. (TS:R is also recommended for RO)
Other than that, its not likely to be a BDB issue so I'll close the issue. If you need further help you probably should bring it up with RO support as you are using that collection of mods.

**Closed** 2024-03-24 04:39 UTC
